### ISSUE TITLE
delete and update

### ISSUE THREAD

**Issue by web3creator** [jean-pierreBoth/hnswlib-rs#11]
First of all, this project is affirmed, I would like to ask how to perform delete and update operations

**Comment by jean-pierreBoth** [comment]
Not possible, at least now.
Possibly you can use filtering (development version) to select/exclude data in search.
If you want to delete a large part of data, I am afraid now it must be done by hand.
Anyway it needs rebuilding all links around deleted items.
Possibly I will add a rebuild with a filter if really useful.
