### ISSUE TITLE
improvement: make HnswIo Sync so it can be shared between threads

### ISSUE THREAD

**Issue by MathGeniusJodie** [jean-pierreBoth/hnswlib-rs#14]
right now I get this error
```
std::cell::RefCell<usize>` cannot be shared between threads safely
within `(std::string::String, hnsw_rs::hnswio::HnswIo)`, the trait `std::marker::Sync` is not implemented for `std::cell::RefCell<usize>`
if you want to do aliasing and mutation between multiple threads, use `std::sync::RwLock` instead
required because it appears within the type `(String, HnswIo)
```

**Comment by jean-pierreBoth** [comment]
I can put nb_point_loaded an AtomicUsize but reading data file will still
be serial. Will that really change the use of hnswio?

Le sam. 27 janv. 2024 à 03:39, MathGeniusJodie ***@***.***> a
écrit :

**Comment by MathGeniusJodie** [comment]
it would be incredibly valuable for async and for integrating with existing multithreaded systems, in fact I'm considering forking this library just for this feature

**Comment by jean-pierreBoth** [comment]
pushed on https://github.com/jean-pierreBoth/hnswlib-rs (not yet on crates.io)
Thanks
