### ISSUE TITLE
Is there a way to append data to existing hnsw file???

### ISSUE THREAD

**Issue by yuyang-ok** [jean-pierreBoth/hnswlib-rs#21]
I already write the `hnsw` file , after that I have some newer data , I want append to existing file.
How can I do this???

**Comment by jean-pierreBoth** [comment]
just reload and insert

**Comment by yuyang-ok** [comment]
should I delete the old files? 
![image](https://github.com/user-attachments/assets/158dc90c-b226-411b-b0ce-834318d08344)

looks generate random files to me

**Comment by jean-pierreBoth** [comment]
No, but care must be taken with names of files as using mmap force dump to
save in name with a random number appended to avoid writing on possibly
mmaped files , this is why you have the files with 4849 appended , and they
are larger. Just overwrite the old files when you are sure no one uses the
old.

**Comment by yuyang-ok** [comment]
But how to overwrite the old file ???
https://docs.rs/hnsw_rs/0.3.0/hnsw_rs/api/trait.AnnT.html#tymethod.file_dump this method have parameter to control `overwrite`.

**Comment by yuyang-ok** [comment]
`load_hnsw` always turn on `datamap_opt`
~~~
 let hnsw : Hnsw::<T,D> =  Hnsw{  max_nb_connection : description.max_nb_connection as usize,
                            ef_construction : description.ef, 
                            extend_candidates : true, 
                            keep_pruned: false,
                            max_layer: description.nb_layer as usize, 
                            layer_indexed_points: layer_point_indexation,
                            data_dimension : data_dim,
                            dist_f: D::default(),
                            searching : false,
                            datamap_opt : true, // set datamap_opt to true
                        } ;
~~~

how to reset this option to overwrite the old file.
